// See https://aka.ms/new-console-template for more information
using FirebaseAdmin;
using FirebaseAdmin.Auth;
using Google.Apis.Auth.OAuth2;

Console.WriteLine("Hello, World!");
FirebaseApp.Create(new AppOptions()
{
    Credential = GoogleCredential.FromFile("firebase-config.json"),
});


string tk = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjViNjAyZTBjYTFmNDdhOGViZmQxMTYwNGQ5Y2JmMDZmNGQ0NWY4MmIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoi7J207KKF7ZuIIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0x0RFVmUFB1UXhfZm1JdzZrTjR3bmtBeTl0d0hRYVdZMEF6V3FkRVA4bD1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9leGVyY2lzZWFwcC1hZmFhZSIsImF1ZCI6ImV4ZXJjaXNlYXBwLWFmYWFlIiwiYXV0aF90aW1lIjoxNzA2NTA5ODc5LCJ1c2VyX2lkIjoieHJjNXZVR3paTFoxaWY4T1RpbXR0bEFpSU1zMSIsInN1YiI6InhyYzV2VUd6WkxaMWlmOE9UaW10dGxBaUlNczEiLCJpYXQiOjE3MDY1MDk4NzksImV4cCI6MTcwNjUxMzQ3OSwiZW1haWwiOiJqb25naG9vbi4xNzM4QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTA4NTg0MjkzODMwOTQ2MDQyNjc1Il0sImVtYWlsIjpbImpvbmdob29uLjE3MzhAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9fQ.crafHtfYOdV7n02hb3QyBeQWTe2LIkfQP8dOG0m8eDS2EZ-UMoShPGmhlThIQThIuTEb_rQERpUAeMHjp1ePcdU__18gDLAUYt3g5F6Lv_7_qbjtAsHvA6cfCtLYcdAatdhN94Ap6lIFvQNiDO9uKUZFW95NZggWoW4qXQmMHOziWtcf8hSkDciD_KxdvPi2ki8rNeumTTRY_YANG";

var decodedToken = await FirebaseAuth.DefaultInstance.VerifyIdTokenAsync(tk);
string uid = decodedToken.Uid;

System.Console.WriteLine(decodedToken.Uid);

